- debug: 
    msg: "Min volume free space in GB: {{ volume.minSize }}"
- debug:
    msg: "Min free space in bytes: {{ (volume.minSize * 1073741824)}}"
- name: Assert root partition need expansion
  assert: 
    that: "{{item.mount != '/' or (item.mount == '/' and item.size_available >  (volume.minSize | float * 1073741824) )}}"  
  with_items: '{{ ansible_mounts }}'
  ignore_errors: yes
  register: expand

- name: Expand partition
  include: 'resize.yml'
  when: expand is failed
